# Generated by Django 5.0.3 on 2024-04-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date_time', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.post')),
                ('social_media_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.socialmediaaccount')),
            ],
            options={
                'verbose_name': 'Postagem Agendada',
                'verbose_name_plural': 'Postagens Agendadas',
            },
        ),
    ]
